name: tic_tac_toe
description: A Flutter Tic Tac Toe game app with a modern UI.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_animate: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo1.jpg
    - assets/fonts/Roboto-Regular.ttf
    - assets/fonts/Roboto-Medium.ttf
    - assets/fonts/Roboto-Bold.ttf
    - assets/fonts/RobotoMono-Regular.ttf
    - assets/fonts/RobotoMono-Light.ttf
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 600
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
        - asset: assets/fonts/RobotoMono-Light.ttf
          weight: 300